### ISSUE TITLE
[API] Endpoint to get all club details

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#100]
The response should include:
- Club's name
- Club's type(Cultural, Science & Technology, etc)
- Club's logo

**Comment by PranshuNayak** [comment]
Can we replace `type` as `category` or only `type` should be used ?

**Comment by Aksh-Bansal-dev** [comment]
I think `category` would make more sense here. Name these whatever you feel is appropriate.
