### ISSUE TITLE
[API] Add model for storing clubs info

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#102]
New app called `clubs` will be created for this model.

This model should have:

- id
- name
- logo
- category (technical, sports etc)
- description
- club's email address

Add more fields if they make sense.

**Comment by PranshuNayak** [comment]
We should include club_email also

**Comment by Samy-33** [comment]
> We should include club_email also

Added.

**Comment by PranshuNayak** [comment]
Using `logo: models.ImageField(upload_to=None)`  as of now . Is it fine?

**Comment by Samy-33** [comment]
Use a [URLField](https://docs.djangoproject.com/en/4.0/ref/models/fields/#urlfield) instead. We would like the models to not worry about the location where the file is stored at. Just the URL.
