### ISSUE TITLE
[API] Add model for Roles

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#103]
There should be a separate app for `ClubRoles` called `roles`. This would signify the relationship between different entities and the users. Example: Club and user's relationship might be a `coordinator`, `co-coordinator`, `faculty incharge` etc.

This model has following fields:

- id
- name (unique name for the role eg. `club-coordinator`
- club
- user
- assigned_at (date at which this role was assigned to the user)
- active (tells whether the role is active or expired)

and other fields if required.

**Comment by PranshuNayak** [comment]
Clubs based on their categories (like cultural,technical etc.) have four more roles i.e `Counselor Associate-Counselor Convener Co-Convener`. `User and Clubs` will be mapped on `one to many relationship` for these roles. In such case for Users which are students may pursue two relationship with the same club.

**Comment by Samy-33** [comment]
> `User and Clubs` will be mapped on `one to many relationship` for these roles. In such case for Users which are students may pursue two relationship with the same club.

The above schema can incorporate one-to-many relationship between user and role. Let me know if you think otherwise.

**Comment by PranshuNayak** [comment]
I think `Class Roles` can be kept as a association class between `User and Clubs` so it need not to have `user` defined in it.

**Comment by Samy-33** [comment]
Sure. Keep a `RoleHolder` model for the relationship between role, club and user.
