### ISSUE TITLE
[API] Add event model to store events' info

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#105]
A new app called `events` should be created for the `Event` model.

`Event` model should have following fields:

- id
- name
- description
- starts_at
- ends_at
- registration_open (false if the event needs registrations otherwise true)
- created_by (the user who created the event)
- image_url (populate a generic default image if none provided)
- club
    - Primary club organizing this event, there could be a case where multiple clubs collaborate for an event. For that scenario, we'll create another model. Let's focus on singleton event organizers for simplicity.
- registration_approval_required 
    - true if the user's registration needs approval from the organizers, otherwise false. If an event registration requires approval, user's request will go to the club's position holders. User's registration will be successful only when it's approved
- address (address where the event is being organized)

Other fields if required. Suggestions for more fields is welcome.

**Comment by PranshuNayak** [comment]
Changes requested:
Change `is_open to registration_open ` & `approval_required to registration_approval_required`

Suggestion:
For multiple clubs organizing the event we can create a `one to many` relationship between `event` and `clubs` and for registration approval_request (if necessary) another `one to many` relationship between `events` and `users`

**Comment by Samy-33** [comment]
> Changes requested:
Change `is_open to registration_open` & `approval_required to registration_approval_required`

Approved.

> Suggestion:
For multiple clubs organizing the event we can create a one to many relationship between event and clubs and for registration approval_request (if necessary) another one to many relationship between events and users

Yes, we'll create models for these one-to-many relationships. First let's add model for the `event`. We'll get better picture on what information will be stored in relationship models.

**Comment by PranshuNayak** [comment]
Agreed!

**Comment by PranshuNayak** [comment]
Are we expecting `DateField or DateTimeField` for starts_at and ends_at

**Comment by PranshuNayak** [comment]
`class Event(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    starts_at = models.DateTimeField()
    ends_at = models.DateTimeField()
    registration_required = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL)
    image_url = models.URLField(max_length=500)
    club = models.ForeignKey(Club, on_delete=models.SET_NULL)
    registration_approval_required = models.BooleanField(default=False)
    address = models.CharField(max_length=255)`
    
    See if this works?
