### ISSUE TITLE
[API] Configure postgres for prod env

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#106]
In `settings.py`, we have configuration for `sqlite3` database. This setting needs to be configured in a way that `sqlite3` is used for local development but in `prod` env, we use `postgres`.

**Comment by brijsiyag** [comment]
We can use separate settings module for dev and prod ?

**Comment by Samy-33** [comment]
> We can use separate settings module for dev and prod ?

This works too.
