### ISSUE TITLE
[UI] Dropdown to filter clubs and events

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#117]
Clubs' dropdown options should include:
- All
- Technical
- Sports
- Cultural
- Registered

Events dropdown options should include:
- Upcoming
- Past

**Comment by PranshuNayak** [comment]
Clubs categories are part of the sidebar in the Figma design file . Are you referring to the same?

**Comment by Aksh-Bansal-dev** [comment]
No. There is a small down arrow on the upcoming carousel heading. That will be the dropdown.
Both clubs and the upcoming carousel will have this.

[figma](https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=0%3A1)
