### ISSUE TITLE
[API] Add an sh script to generate migrations in correct order

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#123]
In multi-app and multi-model django application, migrations are a way to keep track of db schema changes.

And our apps are dependent on each other and ideally should form a Directed Acyclic Graph of dependencies between them.

Everytime the develop needs to run makemigrations (be it first time setup or docker container setup), they should not have to worry about the order in which they have to `makemigrate` the apps.

A bash script that has this order defined will help the developers to skip this highly confusing step to build the app.

- Create a directory called `scripts` in the API `root`.
- Call this script `makemigrations.sh`
- It should be executable
- It should run makemigrations for all the apps that have models, in correct order.

**Comment by arminpatel** [comment]
I'm working on this.

**Comment by arminpatel** [comment]
Order for migrations: api_accounts, api_auth, api_clubs.
Looks right?

**Comment by Samy-33** [comment]
> Order for migrations: api_accounts, api_auth, api_clubs. Looks right?

Yup, and in the end, do a overall `makemigrations` without any app.
