### ISSUE TITLE
[UI] Collapse sidebar on small screens

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#126]
On small screens, only the gymkhana logo should be visible and on clicking it, the sidebar should slide into the screen.
[Figma design](https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=185%3A322). 

You can take a look at [this](https://www.npmjs.com/package/react-modern-drawer) package.

**Comment by prajjwalkapoor** [comment]
I am working on this issue.
