### ISSUE TITLE
[API] Add a delete handler for TokenView

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#130]
### Is your proposal related to a problem?

No. It's related to a feature.
We need to support `logout` feature for users.

### Describe the solution you'd like

- When a DELETE request reaches `/auth/token:revoke`, the token associated with the current user should be deleted from the DB.
- This endpoint is protected. (auth required)

### Describe alternatives you've considered

NA

### Additional Information

Ask away any doubts in the comments.

**Comment by PranshuNayak** [comment]
Any similarity between `auth/token/revoke/` and `auth/token:revoke/`

**Comment by Samy-33** [comment]
https://google.aip.dev/136

It's a custom method.

**Comment by PranshuNayak** [comment]
create a separate view for this ?

**Comment by Samy-33** [comment]
> So we will create a separate `view` for this ?

Yes

**Comment by PranshuNayak** [comment]
- [ ] Create new `view` as `DeleteTokenView` using `DestroyAPIView`
- [ ] Create new `serializer` as `DeleteTokenRequestSerializer` which will obtain `token` sent in the request body
- [ ] Map the view to url `token:token`
- [ ] Create new test class `DeleteTokenViewTest` and define ` testDeleteTokenView_tokenExists_deleteToken`

**Comment by PranshuNayak** [comment]
@Samy-33 is it fine?
