### ISSUE TITLE
[UI] Layout component for pages

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#140]
Home and Profile page have sidebar and topbar in common, so we can make a layout component(`Layout.tsx`) to avoid duplicate code.

[reference](https://github.com/BitByte-TPC/gymkhana/pull/134#discussion_r917298582).

**Comment by mrn97** [comment]
Hi @Aksh-Bansal-dev, cool project thumbs up 👍. I have a problem running your application, I have followed the instructions but when I run the project it takes me to the login page and when I click on sign-in I receive a 400 (invalid_request) error.

error message:
`Missing required parameter: client_id`

could you please help me to find the problem and get it running?

**Comment by Aksh-Bansal-dev** [comment]
You have to get the client_id and client_secret from google console and put those in the `ui/.env` and `api/.env` as mentioned in the docs.

**Comment by mrn97** [comment]
Dear @Aksh-Bansal-dev thanks for your response. now I get 403 error `Error while exchanging auth code for token`. Could you please provide more information about that?

```
Authorized JavaScript origins
URLs1: http://127.0.0.1:3000

Authorized redirect URIs
URLs1: http://127.0.0.1:3000/login/redirect
```

Did I do something wrong here or something else?

**Comment by Aksh-Bansal-dev** [comment]
It should be `http://localhost:3000` instead of `http://127.0.0.1:3000`.

**Comment by Samy-33** [comment]
> Did I do something wrong here or something else?

@mrn97 did you put CLIENT_ID and SECRET you got from google cloud platform to `api/.env`?

**Comment by mrn97** [comment]
error 400 this time. `{"message":"Invalid token issuer. Try again with correct token."}` from the network

**Comment by mrn97** [comment]
Do I have to put them in quotations?

**Comment by mrn97** [comment]
> Do I have to put them in quotations?

Didn't work.

**Comment by prajjwalkapoor** [comment]
I am working on this issue.
