### ISSUE TITLE
[API] Update `Club` model to have registration info

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#153]
Following fields will be added in the Club model

- registration_open (boolean, false by default)
- fee_required (boolean, false by default)
- registration_fee (float, 0.0 by default)

**Comment by PranshuNayak** [comment]
Instead of defining the `circular relationship` can't we just add these three new fields for `registration` and use the `update` operation whenever `registration` opens

**Comment by PranshuNayak** [comment]
> Where do you see the circular relationship?

We are defining `one-to-one relationship` for `club`  inside `club`  🤔🤔? Or is it something else?

**Comment by Samy-33** [comment]
> We are defining `one-to-one relationship` for `club` inside `club` 🤔🤔? So a `club` must exist before it is created ? Or is it something else?

My bad, club shouldn't be there.

**Comment by PranshuNayak** [comment]
I think we need to update  PR [https://github.com/BitByte-TPC/gymkhana/pull/181](url) too for updating these fields

**Comment by PranshuNayak** [comment]
We can also add deadline for `registration`

**Comment by Samy-33** [comment]
Changes will be added in a new PR.
Sure deadline should be added as weoo
