### ISSUE TITLE
[API] Add pagination class for list apis

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#156]
All the list apis need to be paginated according to https://google.aip.dev/132

It also strongly recommends `token` based pagination. But for simplicity we'll use `limit & offset` based pagination for now. 

[Reference](https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination)

**Comment by PranshuNayak** [comment]
`PAGE_SIZE` need to provided ? If yes then what will be it's value

**Comment by Samy-33** [comment]
AFAIU, `LimitOffsetPagination` does not use `PAGE_SIZE`.

**Comment by PranshuNayak** [comment]
Official docs quote 
Optionally, you may also set a `PAGE_SIZE` key. If the `PAGE_SIZE` parameter is also used then the limit query parameter will be optional, and may be omitted by the client

**Comment by Samy-33** [comment]
Let's keep it simple and skip `PAGE_SIZE`

**Comment by PranshuNayak** [comment]
This issue can be closed
