### ISSUE TITLE
[UI] Create a http service for http calls

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#168]
### Is your proposal related to a problem?

No.

### Describe the solution you'd like

Orthogonal feature: A feature that has it's own state and can exist in isolation (on its own). Having our software built with multiple orthogonal features/components makes it modular, reusable and easy to understand.

> This issue is focused on having a service, which will handle all the communication via http.

Currently we are using `fetch` to interact with http servers directly. It places the responsibility to add low-level http details like headers, converting back the response to json etc on the component using `fetch`.

It would be great to have a `HttpService` that will accept the URL, request method, `protected?`, queryparams or body and sends the request to the http-server.

Having a separate `HttpService` allows us to add middlewares for requirements like: adding `Authorization` token to the request if it's a protected endpoint, handle redirection to login page if API returns `HTTP_UNAUTHORIZED` error, conversion of response into a json etc.

Having `HttpService` also allows us to incorporate more http related features in the future without having to modify every single `fetch` call in the application.

### Describe alternatives you've considered

Use third party http library like: `Axios` instead of developing in house http service. Axios also allows us to have middlewares that are the main selling point of having a separate `HttpService`

I want students working on this feature to understand how we create an orthogonal feature in our application.
This would be an exercise and a great way to learn an important concept in software engineering.

### Additional Information

Links:  
- https://www.freecodecamp.org/news/orthogonality-in-software-engineering/
- https://flylib.com/books/en/1.315.1.23/1/
- https://www.codingblocks.net/podcast/the-pragmatic-programmer-is-your-code-orthogonal/

**Comment by Aksh-Bansal-dev** [comment]
Closes by #176?
