### ISSUE TITLE
[API] On fetching data from events return date objects instead on strings

### ISSUE THREAD

**Issue by a1pharooster** [BitByte-TPC/gymkhana#228]
On fetching data from events api we get starts_at and ends_at as strings we should rather get back date objects
![image](https://user-images.githubusercontent.com/73738410/187371405-1897fe3f-6bf6-4bea-80a6-f1fc3b8657ef.png)

return date objects rather than strings

**Comment by Aksh-Bansal-dev** [comment]
I don't think [JSON](https://www.json.org/json-en.html) supports date data type. We can simply [parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) the date string to get the date object.
