### ISSUE TITLE
[UI][Mock] Login Page wireframe

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#27]
Mock should satisfy following requirements:

1. An abstract background, with shapes rolling around slowly.
2. Gymkhana logo (which again abstract, with minimum colors) at the center of the page.
3. A button like `[ICON] Sign In [An arrow to the right]` at the center of the page below the logo.

Once done, please attach a link/image of the design to this issue and ping @BitByte-TPC/gymkhana-ui-devs to review.

**Comment by Samy-33** [comment]
Mock should satisfy following requirements:

1. An abstract background, with shapes rolling around slowly.
2. Gymkhana logo (which again abstract, with minimum colors) at the center of the page.
3. A button like `[ICON] Sign In [An arrow to the right]` at the center of the page below the logo.

Once done, please attach a link/image to the issue and ping @BitByte-TPC/gymkhana-ui-devs to review.

**Comment by PranshuNayak** [comment]
Apart from the requirement of 1st point I want to know whether this is what we are desiring. 

![login](https://user-images.githubusercontent.com/86283785/172049134-ebe11878-6e27-4769-b072-0f093292063c.jpg)

**Comment by Samy-33** [comment]
Yes, something similar. Instead of form input. We just have a medium size button. It should be the most highlighted element on the webpage.

**Comment by Samy-33** [comment]
Wow, these are better than what I imagined. I'd like to go with the 2nd one. But Please do post these two images on the discord group. Let's see what others want.

**Comment by divyanshkhetan** [comment]
@sri2dark The logo seems a bit non-minimalistic to me. Do you have a mockup with the no gradience?

**Comment by sri2dark** [comment]
@di I used this logo for mockup. I guess i will have to design a logo for gymkhana.

**Comment by sri2dark** [comment]
@di I used this logo for mockup. I guess i will have to design a logo for gymkhana.

**Comment by sri2dark** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/84178070/172823253-806802e7-9669-4b88-a249-5d226cc05c0f.jpg)
Mockup of landing page 
link
https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=0%3A1

**Comment by Samy-33** [comment]
@sri2dark, move this to #5

**Comment by sri2dark** [comment]
<img width="1440" alt="Login" src="https://user-images.githubusercontent.com/84178070/173183958-b3491063-327e-4d05-9507-6761e2c46388.png">

**Comment by Manie-oss** [comment]
@sri2dark can you please provide the dark version of the login screen on Figma? As it is required for the dark mode of the web application.

**Comment by sri2dark** [comment]
@Manie-oss I need some time to complete the work .As soon i complete it, i will udapte it.
