### ISSUE TITLE
[GITHUB] Add Issue template

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#35]
We need some issue templates for `bug reports` and `feature requests`.

The purpose of these templates is to have some predefined structure of the Issue when someone opens one.

Documentation for how to: [Issue Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by yusufadell** [comment]
i can do this, could you assign it to me!
