### ISSUE TITLE
[UI][Mock] Gymkhana homepage UI wireframe

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#5]

**Comment by sri2dark** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/84178070/172823253-806802e7-9669-4b88-a249-5d226cc05c0f.jpg)
Mockup of landing page 
link
https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=0%3A1

_Originally posted by @sri2dark in https://github.com/BitByte-TPC/gymkhana/issues/27#issuecomment-1150936255_

**Comment by Manie-oss** [comment]
can this issue be closed if approved??

**Comment by Samy-33** [comment]
@sri2dark, any updates on the design from the last time we synced?

**Comment by sri2dark** [comment]
![Home](https://user-images.githubusercontent.com/84178070/175662647-efee20d5-5581-4ae9-b5e7-babd08e6d440.jpg)
Final mockup of home page @Samy-33

**Comment by Samy-33** [comment]
Looks good to me.

**Comment by sri2dark** [comment]
![13 Pro - 1](https://user-images.githubusercontent.com/84178070/175778149-456ed219-130f-4924-ba72-21be2d1ff59b.png)
![13 Pro - 2](https://user-images.githubusercontent.com/84178070/175778158-c4034bff-92e3-4698-bfd9-84a808114182.png)
Mobile version of home page
