### ISSUE TITLE
[UI] Add both the dark and light themes to website

### ISSUE THREAD

**Issue by akshatnema** [BitByte-TPC/gymkhana#51]
### Description
This issue targets to make scalable styles and global CSS variables which will be helpful in making the website available in both the themes, i.e. dark and light themes. 

**Why do we need this change?**
Presently, UI discussions targets having a single theme on the website whereas the idea may expand to enable the multiple themes in the website (mainly dark and light). Hence, structuring the colors for the website will account for providing suitable themes and will help in the long term bases.

### How to Solve this issue?
This issue targets both the fronted and the design work simultaneously. The UI designer will be finalizing the colors available for the dark and the light themes and then a contributor has to make suitable global CSS variables (`primary`, `secondary`, etc.) for the project so that they can be used effectively. The above implementation of global variables can be done using the `global.css` file or using `Sass` or any suitable CSS library used in the project.

**Comment by Manie-oss** [comment]
I would like to work on this issue.
