### ISSUE TITLE
[UI] Left sidebar

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#68]
Design: [Figma](https://www.figma.com/file/GjOEDxaZ4sT9mBr8A10IiA/Gymkhana?node-id=2%3A2)

- Make it collapsible for small screens.
- Use vanilla CSS only.
- Use CSS variables.
- Leave the 'Contact us' section of the sidebar for now.

**Comment by Samy-33** [comment]
Goal for this issue would be to create a component for the `Sidebar`. Responsibility to collapse would go to the parent component using it.

**Comment by Manie-oss** [comment]
I would like to work on this issue.

**Comment by Aksh-Bansal-dev** [comment]
@Manie-oss are you still working on this?

**Comment by Manie-oss** [comment]
@Aksh-Bansal-dev raised PR.
