### ISSUE TITLE
[API] Restrict authentication to iiitdmj.ac.in

### ISSUE THREAD

**Issue by varisha-025** [BitByte-TPC/gymkhana#73]
Restrict google authentication to users having domain iiitdmj.ac.in. To ensure this, configurations has to be made both on the client side and the server side.

**Comment by Aksh-Bansal-dev** [comment]
I think this can be achieved through the google console when we create the credentials. 

Here, I tried to login using my personal email id.
![Screenshot from 2022-06-13 23-29-52](https://user-images.githubusercontent.com/63552235/173415904-1f1d5cbf-8299-4de4-a2d7-aab34d1db009.png)

**Comment by Samy-33** [comment]
Yup, I verified it. We don't need to handle this on our side. Google restricts the authentication to accounts from `iiitdmj.ac.in` org.
