### ISSUE TITLE
[API] Add fixtures for the local API setup

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#75]
While developing locally, it's always good to have some data to be loaded in the db for a fresh start of the project.

We can achieve that by using `fixtures` in django.

This issue:
- Should put some initial data needed for development in the fixture
- Update documentation on how to load it

Reference: https://docs.djangoproject.com/en/4.0/howto/initial-data/

**Comment by arminpatel** [comment]
>Should put some initial data needed for development in the fixture

Initial data for the User Model?

**Comment by Samy-33** [comment]
@arminpatel, we need following data for now:
- superuser
- Application (oauth2)

@Aksh-Bansal-dev, add if anything else is needed.

**Comment by brijsiyag** [comment]
I'm working on this.

**Comment by Samy-33** [comment]
@brijsiyag, note that we only need a superuser in the fixture for now.
