### ISSUE TITLE
[CI][API] Merge flake8 and api-test workflows into one

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#8]
Currently we have two workflows [api-tests](https://github.com/BitByte-TPC/gymkhana/blob/master/.github/workflows/api-tests.yml) and [api-flake8](https://github.com/BitByte-TPC/gymkhana/blob/master/.github/workflows/api_flake8.yml)

We can merge them together into a single workflow file with two jobs.

Read about Github actions [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)

Start a discussion about your doubts [here](https://github.com/BitByte-TPC/gymkhana/discussions)

**Comment by masterchief164** [comment]
I'd like to work on this issue

**Comment by Samy-33** [comment]
Please go ahead, assigned it to you.
