### ISSUE TITLE
[CI][API] Add coverage checking github action

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#9]
use `coverage.py` and and [pytest-commentator](https://github.com/marketplace/actions/pytest-coverage-commentator) to show it on the PR.

Read about Github actions [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)

Start a discussion about your doubts [here](https://github.com/BitByte-TPC/gymkhana/discussions)

**Comment by divyanshkhetan** [comment]
Can I work on this issue?

**Comment by Samy-33** [comment]
> Can I work on this issue?

Sure @divyanshkhetan, assigned it to you.
