### ISSUE TITLE
[API] Delete expired token, generate new token on create token request

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/gymkhana#90]
To generate an `access_token` for our API, user sends an `id_token` it gets after authenticating on Google to `/auth/token`.

If user sends request to `/auth/token` and the token is expired, current logic returns the expired token. This should be fixed.

We need:
1. Delete the token if it's expired.
2. Create a new token and return it in the response.

**Comment by PranshuNayak** [comment]
`user = self._find_or_create_user(user_info)
 access_token = Token.find_or_create(user)
return Response(data=CreateTokenResponseSerializer(access_token).data)`

You are referring to this?

**Comment by Samy-33** [comment]
> You are referring to this?

Yes, here if you get an expired token, delete it and return a new one.

**Comment by PranshuNayak** [comment]
So the everytime user send request to `/auth/token/` it sends a new `authorization_code` ?
