### ISSUE TITLE
[UI] Add a linting rule for no console logs

### ISSUE THREAD

**Issue by Aksh-Bansal-dev** [BitByte-TPC/gymkhana#95]

**Comment by PranshuNayak** [comment]
@Aksh-Bansal-dev I have added the lint rule and it is correctly reporting the error but on running npm run lint:fix it is not fixing the error. What should I do next ?

**Comment by Aksh-Bansal-dev** [comment]
Just create a PR.
`npm run lint:fix` does not fix all errors/warnings. 
Reference [ESLint docs](https://eslint.org/docs/latest/user-guide/command-line-interface#fixing-problems).

**Comment by Samy-33** [comment]
![image](https://user-images.githubusercontent.com/15676805/176122332-8cab38ad-3665-4605-9015-655be7451a1a.png)

If you can fix those errors along in this PR.
